# 第一阶段：使用 Node.js 镜像构建静态文件
FROM node:10.15.3 AS builder

# 设置工作目录
WORKDIR /app

# 复制前端源代码到工作目录
COPY ./front-end /app

# 安装依赖并构建静态文件
RUN npm install && npm run build

# 第二阶段：使用 Nginx 镜像
FROM nginx:latest

# 将从第一阶段构建的静态文件复制到 Nginx 工作目录中
COPY --from=builder /app/dist/ /usr/share/nginx/html/

# （可选）复制 Nginx 配置文件
# COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
